services:
  owl.registry.date_provider_filter:
    class: Owl\Shared\Domain\DataProvider\Registry\FilterRegistry
    arguments:
      - 'Owl\Shared\Domain\DataProvider\Filter\FilterInterface'
      - 'data provider filter'

  owl.data_provider.doctrine.orm.collection_data_provider:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\CollectionDataProvider
    arguments:
      - '@owl.data_provider.doctrine.orm.factory_query_builder'
      - !tagged_iterator data_provider.doctrine.orm.applicator.collection

  owl.data_provider.doctrine.orm.item_data_provider:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\ItemDataProvider
    arguments:
      - '@owl.data_provider.doctrine.orm.factory_query_builder'
      - !tagged_iterator data_provider.doctrine.orm.applicator.item

  owl.data_provider.doctrine.request_params_factory:
    class: Owl\Shared\Domain\DataProvider\Factory\RequestParamsFactory
    arguments:
      - '%data_provider%'

  owl.data_provider.doctrine.orm.factory_query_builder:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\Factory\QueryBuilderFactory
    arguments:
      - '@doctrine'

  owl.data_provider.doctrine.orm.filter_applicator:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\Applicator\FilterApplicator
    arguments:
      - '@owl.data_provider.doctrine.orm.field_resolver'
      - '@owl.registry.date_provider_filter'
    tags:
      - { name: data_provider.doctrine.orm.applicator.collection, priority: -64 }

  owl.data_provider.doctrine.orm.sort_applicator:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\Applicator\SortApplicator
    arguments:
      - '@owl.data_provider.doctrine.orm.field_resolver'
    tags:
      - { name: data_provider.doctrine.orm.applicator.collection, priority: -96 }

  owl.data_provider.doctrine.orm.pagination_applicator:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\Applicator\PaginationApplicator
    tags:
      - { name: data_provider.doctrine.orm.applicator.collection, priority: -128 }

  owl.data_provider.doctrine.orm.identifiers_applicator:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\Applicator\IdentifiersApplicator
    arguments:
      - '@owl.data_provider.doctrine.orm.field_resolver'
    tags:
      - { name: data_provider.doctrine.orm.applicator.item, priority: -128 }

  Owl\Shared\Infrastructure\Symfony\Http\ArgumentResolver\RequestDataProviderParamsResolver:
      arguments:
        - '@owl.data_provider.doctrine.request_params_factory'
      tags:
        - { name: controller.argument_value_resolver, priority: 64 }

  owl.data_provider.doctrine.orm.field_resolver:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\Resolver\FieldResolver

  Owl\Shared\Infrastructure\DataProvider\Orm\Bus\Query\ItemQueryHandler:
      autoconfigure: false
      arguments: 
        - '@owl.data_provider.doctrine.orm.item_data_provider'
      tags:
        -
          bus: query.bus
          name: messenger.message_handler
          handles: Owl\Shared\Infrastructure\DataProvider\Orm\Bus\Query\ItemQuery

  Owl\Shared\Infrastructure\DataProvider\Orm\Bus\Query\CollectionQueryHandler:
      autoconfigure: false
      arguments: 
        - '@owl.data_provider.doctrine.orm.collection_data_provider'
      tags:
        -
          bus: query.bus
          name: messenger.message_handler
          handles: Owl\Shared\Infrastructure\DataProvider\Orm\Bus\Query\CollectionQuery


