article_get_list:
  path: /api/articles
  controller: Owl\Apps\Api\Controller\Article\ArticleListController
  methods:  [GET]
  defaults:
    auth: false
    data_provider:
      sorting:
        default_sort:
          title: desc

article_get:
  path: /api/articles/{id}
  controller: Owl\Apps\Api\Controller\Article\ArticleGetController
  defaults: { auth: false }
  methods:  [GET]

article_post:
  path: /api/articles
  controller: Owl\Apps\Api\Controller\Article\ArticlePostController
  defaults: { auth: false }
  methods:  [POST]
