article_get:
  path: /api/articles
  controller: Owl\Apps\Api\Controller\Article\ArticleListController
  methods:  [GET]
  defaults:
    auth: false
    data_provider:
      sorting:
        default_sort:
          title: desc

article_get_bus:
  path: /api/articles-bus
  controller: Owl\Apps\Api\Controller\Article\ArticleListBusController
  methods:  [GET]
  defaults:
    auth: false
    data_provider:
      sorting:
        default_sort:
          title: desc


article_post:
  path: /api/articles
  controller: Owl\Apps\Api\Controller\Article\ArticlePostController
  defaults: { auth: false }
  methods:  [POST]
